// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for Contact documents */
interface ContactDocumentData {
  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Gallery documents */
interface GalleryDocumentData {
  /**
   * Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Gallery*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;
/** Content for Globals documents */
interface GlobalsDocumentData {
  /**
   * Menu field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menu: prismic.GroupField<Simplify<GlobalsDocumentDataMenuItem>>;
  /**
   * Footer Policies field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  footerPolicies: prismic.GroupField<
    Simplify<GlobalsDocumentDataFooterPoliciesItem>
  >;
  /**
   * Social Links field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialLinks: prismic.GroupField<Simplify<GlobalsDocumentDataSocialLinksItem>>;
  /**
   * Address field in *Globals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  contactAddress: prismic.RichTextField;
  /**
   * Location field in *Globals*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactLocation
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
   *
   */
  contactLocation: prismic.GeoPointField;
  /**
   * Map Link field in *Globals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactMapLink
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  contactMapLink: prismic.LinkField;
  /**
   * Email Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactEmailAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactEmailAddress: prismic.KeyTextField;
  /**
   * Telephone Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactNumber
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactNumber: prismic.KeyTextField;
}
/**
 * Item in Globals → Menu
 *
 */
export interface GlobalsDocumentDataMenuItem {
  /**
   * Link field in *Globals → Menu*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.RelationField;
  /**
   * Label field in *Globals → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Footer Policies
 *
 */
export interface GlobalsDocumentDataFooterPoliciesItem {
  /**
   * Link field in *Globals → Footer Policies*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.RelationField<"legal">;
  /**
   * Label field in *Globals → Footer Policies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Social Links
 *
 */
export interface GlobalsDocumentDataSocialLinksItem {
  /**
   * Platform field in *Globals → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: globals.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  platform: prismic.SelectField<
    "Instagram" | "Twitter" | "Facebook" | "Linkedin",
    "filled"
  >;
  /**
   * Link field in *Globals → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Tagline field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLabel
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heroCtaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLink
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  heroCtaLink: prismic.LinkField;
  /**
   * Hero Images field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[]
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  heroImages: prismic.GroupField<Simplify<HomepageDocumentDataHeroImagesItem>>;
  /**
   * Text Blocks field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[]
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  introTextBlocks: prismic.GroupField<
    Simplify<HomepageDocumentDataIntroTextBlocksItem>
  >;
  /**
   * Image 1 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage1
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage1: prismic.ImageField<never>;
  /**
   * Image 2 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage2
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage2: prismic.ImageField<never>;
  /**
   * Image 3 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage3
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage3: prismic.ImageField<never>;
  /**
   * Quotes field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.quotes[]
   * - **Tab**: Quotes
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  quotes: prismic.GroupField<Simplify<HomepageDocumentDataQuotesItem>>;
  /**
   * Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.aboutImage
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  aboutImage: prismic.ImageField<"Narrow Screen">;
  /**
   * Heading field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.aboutHeading
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  aboutHeading: prismic.KeyTextField;
  /**
   * Body field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.aboutBody
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  aboutBody: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.aboutCtaLabel
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  aboutCtaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.aboutCtaLink
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  aboutCtaLink: prismic.LinkField;
  /**
   * Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contactImage
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  contactImage: prismic.ImageField<"Narrow Screen">;
  /**
   * Heading field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contactHeading
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactHeading: prismic.KeyTextField;
  /**
   * Body field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contactBody
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  contactBody: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contactCtaLabel
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactCtaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contactCtaLink
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  contactCtaLink: prismic.LinkField;
}
/**
 * Item in Homepage → Hero Images
 *
 */
export interface HomepageDocumentDataHeroImagesItem {
  /**
   * Image field in *Homepage → Hero Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"portrait">;
}
/**
 * Item in Homepage → Text Blocks
 *
 */
export interface HomepageDocumentDataIntroTextBlocksItem {
  /**
   * Text field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
}
/**
 * Item in Homepage → Quotes
 *
 */
export interface HomepageDocumentDataQuotesItem {
  /**
   * Quote field in *Homepage → Quotes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.quotes[].quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismic.RichTextField;
  /**
   * Attribution field in *Homepage → Quotes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.quotes[].attribution
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  attribution: prismic.KeyTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Legal documents */
interface LegalDocumentData {
  /**
   * Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;
/** Content for Testimonials documents */
interface TestimonialsDocumentData {
  /**
   * Title field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Testimonials document from Prismic
 *
 * - **API ID**: `testimonials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestimonialsDocumentData>,
    "testimonials",
    Lang
  >;
/** Content for The Studio documents */
interface TheStudioDocumentData {
  /**
   * Title field in *The Studio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *The Studio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *The Studio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *The Studio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * The Studio document from Prismic
 *
 * - **API ID**: `theStudio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheStudioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheStudioDocumentData>,
    "theStudio",
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | GalleryDocument
  | GlobalsDocument
  | HomepageDocument
  | LegalDocument
  | TestimonialsDocument
  | TheStudioDocument;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocument,
      ContactDocumentData,
      ContactDocument,
      GalleryDocumentData,
      GalleryDocument,
      GlobalsDocumentData,
      GlobalsDocumentDataMenuItem,
      GlobalsDocumentDataFooterPoliciesItem,
      GlobalsDocumentDataSocialLinksItem,
      GlobalsDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroImagesItem,
      HomepageDocumentDataIntroTextBlocksItem,
      HomepageDocumentDataQuotesItem,
      HomepageDocument,
      LegalDocumentData,
      LegalDocument,
      TestimonialsDocumentData,
      TestimonialsDocument,
      TheStudioDocumentData,
      TheStudioDocument,
      AllDocumentTypes,
    };
  }
}
