// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.heroImage
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  heroImage: prismic.ImageField<"wide" | "square" | "portrait">;
  /**
   * Tagline field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * Text Colour field in *About*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: about.textColor
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  textColor: prismic.SelectField<"Light" | "Dark", "filled">;
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices2: prismic.SliceZone<AboutDocumentDataSlices2Slice>;
}
/**
 * Slice for *About → Slice Zone*
 *
 */
type AboutDocumentDataSlices2Slice =
  | QuotesBlockSlice
  | TextBlockSlice
  | WideImageBlockSlice;
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for Contact documents */
interface ContactDocumentData {
  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Gallery documents */
interface GalleryDocumentData {
  /**
   * Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Gallery*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;
/** Content for Globals documents */
interface GlobalsDocumentData {
  /**
   * Menu field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menu: prismic.GroupField<Simplify<GlobalsDocumentDataMenuItem>>;
  /**
   * Footer Policies field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  footerPolicies: prismic.GroupField<
    Simplify<GlobalsDocumentDataFooterPoliciesItem>
  >;
  /**
   * Social Links field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialLinks: prismic.GroupField<Simplify<GlobalsDocumentDataSocialLinksItem>>;
  /**
   * Address field in *Globals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  contactAddress: prismic.RichTextField;
  /**
   * Location field in *Globals*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactLocation
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
   *
   */
  contactLocation: prismic.GeoPointField;
  /**
   * Map Link field in *Globals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactMapLink
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  contactMapLink: prismic.LinkField;
  /**
   * Email Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactEmailAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactEmailAddress: prismic.KeyTextField;
  /**
   * Telephone Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactNumber
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactNumber: prismic.KeyTextField;
  /**
   * Slides field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.slides[]
   * - **Tab**: Footer Slides
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  slides: prismic.GroupField<Simplify<GlobalsDocumentDataSlidesItem>>;
}
/**
 * Item in Globals → Menu
 *
 */
export interface GlobalsDocumentDataMenuItem {
  /**
   * Link field in *Globals → Menu*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField;
  /**
   * Label field in *Globals → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Footer Policies
 *
 */
export interface GlobalsDocumentDataFooterPoliciesItem {
  /**
   * Link field in *Globals → Footer Policies*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField<"legal">;
  /**
   * Label field in *Globals → Footer Policies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Social Links
 *
 */
export interface GlobalsDocumentDataSocialLinksItem {
  /**
   * Platform field in *Globals → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: globals.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  platform: prismic.SelectField<
    "Instagram" | "Twitter" | "Facebook" | "Linkedin",
    "filled"
  >;
  /**
   * Link field in *Globals → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Item in Globals → Slides
 *
 */
export interface GlobalsDocumentDataSlidesItem {
  /**
   * Image field in *Globals → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.slides[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Tagline field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLabel
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heroCtaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLink
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  heroCtaLink: prismic.LinkField;
  /**
   * Hero Images field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[]
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  heroImages: prismic.GroupField<Simplify<HomepageDocumentDataHeroImagesItem>>;
  /**
   * Text Blocks field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[]
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  introTextBlocks: prismic.GroupField<
    Simplify<HomepageDocumentDataIntroTextBlocksItem>
  >;
  /**
   * Image 1 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage1
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage1: prismic.ImageField<never>;
  /**
   * Image 2 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage2
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage2: prismic.ImageField<never>;
  /**
   * Image 3 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage3
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage3: prismic.ImageField<never>;
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices7[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices7: prismic.SliceZone<HomepageDocumentDataSlices7Slice>;
}
/**
 * Item in Homepage → Hero Images
 *
 */
export interface HomepageDocumentDataHeroImagesItem {
  /**
   * Image field in *Homepage → Hero Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"wide" | "square" | "portrait">;
}
/**
 * Item in Homepage → Text Blocks
 *
 */
export interface HomepageDocumentDataIntroTextBlocksItem {
  /**
   * Text field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlices7Slice =
  | QuotesBlockSlice
  | FullscreenTextWithImageBlockSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Legal documents */
interface LegalDocumentData {
  /**
   * Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;
/** Content for Testimonials documents */
interface TestimonialsDocumentData {
  /**
   * Title field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Testimonials document from Prismic
 *
 * - **API ID**: `testimonials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestimonialsDocumentData>,
    "testimonials",
    Lang
  >;
/** Content for The Studio documents */
interface TheStudioDocumentData {
  /**
   * Title field in *The Studio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *The Studio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *The Studio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *The Studio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theStudio.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * The Studio document from Prismic
 *
 * - **API ID**: `theStudio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TheStudioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TheStudioDocumentData>,
    "theStudio",
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | GalleryDocument
  | GlobalsDocument
  | HomepageDocument
  | LegalDocument
  | TestimonialsDocument
  | TheStudioDocument;
/**
 * Primary content in EmphasisBlock → Primary
 *
 */
interface EmphasisBlockSliceDefaultPrimary {
  /**
   * Body field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
}
/**
 * Default variation for EmphasisBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmphasisBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmphasisBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *EmphasisBlock*
 *
 */
type EmphasisBlockSliceVariation = EmphasisBlockSliceDefault;
/**
 * EmphasisBlock Shared Slice
 *
 * - **API ID**: `emphasis_block`
 * - **Description**: `EmphasisBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmphasisBlockSlice = prismic.SharedSlice<
  "emphasis_block",
  EmphasisBlockSliceVariation
>;
/**
 * Primary content in FullscreenTextWithImageBlock → Primary
 *
 */
interface FullscreenTextWithImageBlockSliceDefaultPrimary {
  /**
   * Arrangement field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: fullscreen_text_with_image_block.primary.isImageOnRight
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  isImageOnRight: prismic.BooleanField;
  /**
   * Heading field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
  /**
   * Image field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"SmallScreen">;
}
/**
 * Default variation for FullscreenTextWithImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenTextWithImageBlockSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FullscreenTextWithImageBlockSliceDefaultPrimary>,
    never
  >;
/**
 * Slice variation for *FullscreenTextWithImageBlock*
 *
 */
type FullscreenTextWithImageBlockSliceVariation =
  FullscreenTextWithImageBlockSliceDefault;
/**
 * FullscreenTextWithImageBlock Shared Slice
 *
 * - **API ID**: `fullscreen_text_with_image_block`
 * - **Description**: `FullscreenTextWithImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenTextWithImageBlockSlice = prismic.SharedSlice<
  "fullscreen_text_with_image_block",
  FullscreenTextWithImageBlockSliceVariation
>;
/**
 * Item in QuotesBlock → Items
 *
 */
export interface QuotesBlockSliceDefaultItem {
  /**
   * Quote field in *QuotesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes_block.items[].quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismic.RichTextField;
  /**
   * Attribution field in *QuotesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes_block.items[].attribution
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  attribution: prismic.KeyTextField;
}
/**
 * Default variation for QuotesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<QuotesBlockSliceDefaultItem>
>;
/**
 * Slice variation for *QuotesBlock*
 *
 */
type QuotesBlockSliceVariation = QuotesBlockSliceDefault;
/**
 * QuotesBlock Shared Slice
 *
 * - **API ID**: `quotes_block`
 * - **Description**: `QuotesBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesBlockSlice = prismic.SharedSlice<
  "quotes_block",
  QuotesBlockSliceVariation
>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
  /**
   * Heading field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceTextBlockWithCtaPrimary {
  /**
   * Heading field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *TextBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
}
/**
 * Text Block with CTA variation for TextBlock Slice
 *
 * - **API ID**: `textBlockWithCta`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceTextBlockWithCta = prismic.SharedSliceVariation<
  "textBlockWithCta",
  Simplify<TextBlockSliceTextBlockWithCtaPrimary>,
  never
>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTextBlockWithCta;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;
/**
 * Primary content in WideImageBlock → Primary
 *
 */
interface WideImageBlockSliceDefaultPrimary {
  /**
   * Image field in *WideImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: wide_image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"SmallScreen">;
  /**
   * Caption field in *WideImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wide_image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismic.KeyTextField;
}
/**
 * Default variation for WideImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WideImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WideImageBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *WideImageBlock*
 *
 */
type WideImageBlockSliceVariation = WideImageBlockSliceDefault;
/**
 * WideImageBlock Shared Slice
 *
 * - **API ID**: `wide_image_block`
 * - **Description**: `WideImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WideImageBlockSlice = prismic.SharedSlice<
  "wide_image_block",
  WideImageBlockSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocumentDataSlices2Slice,
      AboutDocument,
      ContactDocumentData,
      ContactDocument,
      GalleryDocumentData,
      GalleryDocument,
      GlobalsDocumentData,
      GlobalsDocumentDataMenuItem,
      GlobalsDocumentDataFooterPoliciesItem,
      GlobalsDocumentDataSocialLinksItem,
      GlobalsDocumentDataSlidesItem,
      GlobalsDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroImagesItem,
      HomepageDocumentDataIntroTextBlocksItem,
      HomepageDocumentDataSlices7Slice,
      HomepageDocument,
      LegalDocumentData,
      LegalDocument,
      TestimonialsDocumentData,
      TestimonialsDocument,
      TheStudioDocumentData,
      TheStudioDocument,
      AllDocumentTypes,
      EmphasisBlockSliceDefaultPrimary,
      EmphasisBlockSliceDefault,
      EmphasisBlockSliceVariation,
      EmphasisBlockSlice,
      FullscreenTextWithImageBlockSliceDefaultPrimary,
      FullscreenTextWithImageBlockSliceDefault,
      FullscreenTextWithImageBlockSliceVariation,
      FullscreenTextWithImageBlockSlice,
      QuotesBlockSliceDefaultItem,
      QuotesBlockSliceDefault,
      QuotesBlockSliceVariation,
      QuotesBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceDefault,
      TextBlockSliceTextBlockWithCtaPrimary,
      TextBlockSliceTextBlockWithCta,
      TextBlockSliceVariation,
      TextBlockSlice,
      WideImageBlockSliceDefaultPrimary,
      WideImageBlockSliceDefault,
      WideImageBlockSliceVariation,
      WideImageBlockSlice,
    };
  }
}
