// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Contact documents */
interface ContactDocumentData {
  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<never>;
  /**
   * Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.heroImage
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  heroImage: prismic.ImageField<"wide" | "square" | "portrait">;
  /**
   * Tagline field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * Text Colour field in *Contact*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: contact.heroTextColor
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  heroTextColor: prismic.SelectField<"Light" | "Dark", "filled">;
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices2: prismic.SliceZone<ContactDocumentDataSlices2Slice>;
}
/**
 * Slice for *Contact → Slice Zone*
 *
 */
type ContactDocumentDataSlices2Slice =
  | TextBlockSlice
  | WideImageBlockSlice
  | EmphasisBlockSlice;
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Content Page documents */
interface ContentPageDocumentData {
  /**
   * Title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Content Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<never>;
  /**
   * Image field in *Content Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.heroImage
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  heroImage: prismic.ImageField<"wide" | "square" | "portrait">;
  /**
   * Tagline field in *Content Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * Text Colour field in *Content Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: contentPage.heroTextColor
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  heroTextColor: prismic.SelectField<"Light" | "Dark", "filled">;
  /**
   * Slice Zone field in *Content Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.slices2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices2: prismic.SliceZone<ContentPageDocumentDataSlices2Slice>;
}
/**
 * Slice for *Content Page → Slice Zone*
 *
 */
type ContentPageDocumentDataSlices2Slice =
  | TextBlockSlice
  | WideImageBlockSlice
  | QuotesBlockSlice
  | EmphasisBlockSlice
  | TestimonialBlockSlice
  | ImageCarouselBlockSlice;
/**
 * Content Page document from Prismic
 *
 * - **API ID**: `contentPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentPageDocumentData>,
    "contentPage",
    Lang
  >;
/** Content for Globals documents */
interface GlobalsDocumentData {
  /**
   * Menu field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menu: prismic.GroupField<Simplify<GlobalsDocumentDataMenuItem>>;
  /**
   * Footer Policies field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[]
   * - **Tab**: Navigations
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  footerPolicies: prismic.GroupField<
    Simplify<GlobalsDocumentDataFooterPoliciesItem>
  >;
  /**
   * Social Links field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socialLinks: prismic.GroupField<Simplify<GlobalsDocumentDataSocialLinksItem>>;
  /**
   * Address field in *Globals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  contactAddress: prismic.RichTextField;
  /**
   * Location field in *Globals*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactLocation
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
   *
   */
  contactLocation: prismic.GeoPointField;
  /**
   * Map Link field in *Globals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactMapLink
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  contactMapLink: prismic.LinkField;
  /**
   * Email Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactEmailAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactEmailAddress: prismic.KeyTextField;
  /**
   * Telephone Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactNumber
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contactNumber: prismic.KeyTextField;
  /**
   * Slides field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.slides[]
   * - **Tab**: Footer Slides
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  slides: prismic.GroupField<Simplify<GlobalsDocumentDataSlidesItem>>;
}
/**
 * Item in Globals → Menu
 *
 */
export interface GlobalsDocumentDataMenuItem {
  /**
   * Link field in *Globals → Menu*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField;
  /**
   * Label field in *Globals → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.menu[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Footer Policies
 *
 */
export interface GlobalsDocumentDataFooterPoliciesItem {
  /**
   * Link field in *Globals → Footer Policies*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField<"legal">;
  /**
   * Label field in *Globals → Footer Policies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.footerPolicies[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
}
/**
 * Item in Globals → Social Links
 *
 */
export interface GlobalsDocumentDataSocialLinksItem {
  /**
   * Platform field in *Globals → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: globals.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  platform: prismic.SelectField<
    "Instagram" | "Twitter" | "Facebook" | "Linkedin",
    "filled"
  >;
  /**
   * Link field in *Globals → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Item in Globals → Slides
 *
 */
export interface GlobalsDocumentDataSlidesItem {
  /**
   * Image field in *Globals → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.slides[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<never>;
  /**
   * Tagline field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLabel
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heroCtaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCtaLink
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  heroCtaLink: prismic.LinkField;
  /**
   * Hero Images field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[]
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  heroImages: prismic.GroupField<Simplify<HomepageDocumentDataHeroImagesItem>>;
  /**
   * Text Colour field in *Homepage*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: homepage.heroTextColor
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  heroTextColor: prismic.SelectField<"Light" | "Dark", "filled">;
  /**
   * Text Blocks field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[]
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  introTextBlocks: prismic.GroupField<
    Simplify<HomepageDocumentDataIntroTextBlocksItem>
  >;
  /**
   * Image 1 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage1
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage1: prismic.ImageField<never>;
  /**
   * Image 2 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage2
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage2: prismic.ImageField<never>;
  /**
   * Image 3 field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImage3
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  introImage3: prismic.ImageField<never>;
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices7[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices7: prismic.SliceZone<HomepageDocumentDataSlices7Slice>;
}
/**
 * Item in Homepage → Hero Images
 *
 */
export interface HomepageDocumentDataHeroImagesItem {
  /**
   * Image field in *Homepage → Hero Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroImages[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"wide" | "square" | "portrait">;
}
/**
 * Item in Homepage → Text Blocks
 *
 */
export interface HomepageDocumentDataIntroTextBlocksItem {
  /**
   * Text field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * CTA Label field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
  /**
   * CTA Link field in *Homepage → Text Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introTextBlocks[].ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlices7Slice =
  | FullscreenTextWithImageBlockSlice
  | QuotesBlockSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Landing Page documents */
interface LandingPageDocumentData {
  /**
   * Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<never>;
  /**
   * Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.heroImage
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  heroImage: prismic.ImageField<"wide" | "square" | "portrait">;
  /**
   * Tagline field in *Landing Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.heroTagline
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTagline: prismic.RichTextField;
  /**
   * Text Colour field in *Landing Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: landingPage.heroTextColor
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  heroTextColor: prismic.SelectField<"Light" | "Dark", "filled">;
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.slices2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices2: prismic.SliceZone<LandingPageDocumentDataSlices2Slice>;
}
/**
 * Slice for *Landing Page → Slice Zone*
 *
 */
type LandingPageDocumentDataSlices2Slice =
  | TextBlockSlice
  | WideImageBlockSlice
  | QuotesBlockSlice
  | EmphasisBlockSlice
  | ImageCarouselBlockSlice;
/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landingPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landingPage",
    Lang
  >;
/** Content for Legal documents */
interface LegalDocumentData {
  /**
   * Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Summary field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.summary
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  summary: prismic.KeyTextField;
  /**
   * Primary Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.primaryImage
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  primaryImage: prismic.ImageField<"meta">;
  /**
   * Body field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;
export type AllDocumentTypes =
  | ContactDocument
  | ContentPageDocument
  | GlobalsDocument
  | HomepageDocument
  | LandingPageDocument
  | LegalDocument;
/**
 * Primary content in ContactBlock → Primary
 *
 */
interface ContactBlockSliceDefaultPrimary {
  /**
   * Title field in *ContactBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Intro field in *ContactBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.intro
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  intro: prismic.RichTextField;
}
/**
 * Default variation for ContactBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ContactBlock*
 *
 */
type ContactBlockSliceVariation = ContactBlockSliceDefault;
/**
 * ContactBlock Shared Slice
 *
 * - **API ID**: `contact_block`
 * - **Description**: `ContactBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactBlockSlice = prismic.SharedSlice<
  "contact_block",
  ContactBlockSliceVariation
>;
/**
 * Primary content in EmphasisBlock → Primary
 *
 */
interface EmphasisBlockSliceDefaultPrimary {
  /**
   * Body field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *EmphasisBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: emphasis_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
}
/**
 * Default variation for EmphasisBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmphasisBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmphasisBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *EmphasisBlock*
 *
 */
type EmphasisBlockSliceVariation = EmphasisBlockSliceDefault;
/**
 * EmphasisBlock Shared Slice
 *
 * - **API ID**: `emphasis_block`
 * - **Description**: `EmphasisBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmphasisBlockSlice = prismic.SharedSlice<
  "emphasis_block",
  EmphasisBlockSliceVariation
>;
/**
 * Primary content in FullscreenTextWithImageBlock → Primary
 *
 */
interface FullscreenTextWithImageBlockSliceDefaultPrimary {
  /**
   * Arrangement field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: fullscreen_text_with_image_block.primary.isImageOnRight
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  isImageOnRight: prismic.BooleanField;
  /**
   * Heading field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
  /**
   * Image field in *FullscreenTextWithImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_text_with_image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"SmallScreen">;
}
/**
 * Default variation for FullscreenTextWithImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenTextWithImageBlockSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FullscreenTextWithImageBlockSliceDefaultPrimary>,
    never
  >;
/**
 * Slice variation for *FullscreenTextWithImageBlock*
 *
 */
type FullscreenTextWithImageBlockSliceVariation =
  FullscreenTextWithImageBlockSliceDefault;
/**
 * FullscreenTextWithImageBlock Shared Slice
 *
 * - **API ID**: `fullscreen_text_with_image_block`
 * - **Description**: `FullscreenTextWithImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenTextWithImageBlockSlice = prismic.SharedSlice<
  "fullscreen_text_with_image_block",
  FullscreenTextWithImageBlockSliceVariation
>;
/**
 * Item in ImageCarouselBlock → Items
 *
 */
export interface ImageCarouselBlockSliceDefaultItem {
  /**
   * Image field in *ImageCarouselBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel_block.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Caption (optional) field in *ImageCarouselBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel_block.items[].caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismic.KeyTextField;
}
/**
 * Default variation for ImageCarouselBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageCarouselBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageCarouselBlockSliceDefaultItem>
>;
/**
 * Slice variation for *ImageCarouselBlock*
 *
 */
type ImageCarouselBlockSliceVariation = ImageCarouselBlockSliceDefault;
/**
 * ImageCarouselBlock Shared Slice
 *
 * - **API ID**: `image_carousel_block`
 * - **Description**: `ImageCarouselBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageCarouselBlockSlice = prismic.SharedSlice<
  "image_carousel_block",
  ImageCarouselBlockSliceVariation
>;
/**
 * Item in QuotesBlock → Items
 *
 */
export interface QuotesBlockSliceDefaultItem {
  /**
   * Quote field in *QuotesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes_block.items[].quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismic.RichTextField;
  /**
   * Attribution field in *QuotesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes_block.items[].attribution
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  attribution: prismic.KeyTextField;
}
/**
 * Default variation for QuotesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<QuotesBlockSliceDefaultItem>
>;
/**
 * Slice variation for *QuotesBlock*
 *
 */
type QuotesBlockSliceVariation = QuotesBlockSliceDefault;
/**
 * QuotesBlock Shared Slice
 *
 * - **API ID**: `quotes_block`
 * - **Description**: `QuotesBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesBlockSlice = prismic.SharedSlice<
  "quotes_block",
  QuotesBlockSliceVariation
>;
/**
 * Primary content in TestimonialBlock → Primary
 *
 */
interface TestimonialBlockSliceDefaultPrimary {
  /**
   * Testimonial field in *TestimonialBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_block.primary.testimonial
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  testimonial: prismic.RichTextField;
  /**
   * Attribution field in *TestimonialBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_block.primary.attribution
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  attribution: prismic.KeyTextField;
}
/**
 * Default variation for TestimonialBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TestimonialBlock*
 *
 */
type TestimonialBlockSliceVariation = TestimonialBlockSliceDefault;
/**
 * TestimonialBlock Shared Slice
 *
 * - **API ID**: `testimonial_block`
 * - **Description**: `TestimonialBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialBlockSlice = prismic.SharedSlice<
  "testimonial_block",
  TestimonialBlockSliceVariation
>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
  /**
   * Heading field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceTextBlockWithCtaPrimary {
  /**
   * Heading field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * Body field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField;
  /**
   * CTA Link field in *TextBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctaLink: prismic.LinkField;
  /**
   * CTA Label field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ctaLabel: prismic.KeyTextField;
}
/**
 * Text Block with CTA variation for TextBlock Slice
 *
 * - **API ID**: `textBlockWithCta`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceTextBlockWithCta = prismic.SharedSliceVariation<
  "textBlockWithCta",
  Simplify<TextBlockSliceTextBlockWithCtaPrimary>,
  never
>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTextBlockWithCta;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;
/**
 * Primary content in WideImageBlock → Primary
 *
 */
interface WideImageBlockSliceDefaultPrimary {
  /**
   * Image field in *WideImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: wide_image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"SmallScreen">;
  /**
   * Caption field in *WideImageBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wide_image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismic.KeyTextField;
}
/**
 * Default variation for WideImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WideImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WideImageBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *WideImageBlock*
 *
 */
type WideImageBlockSliceVariation = WideImageBlockSliceDefault;
/**
 * WideImageBlock Shared Slice
 *
 * - **API ID**: `wide_image_block`
 * - **Description**: `WideImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WideImageBlockSlice = prismic.SharedSlice<
  "wide_image_block",
  WideImageBlockSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ContactDocumentData,
      ContactDocumentDataSlices2Slice,
      ContactDocument,
      ContentPageDocumentData,
      ContentPageDocumentDataSlices2Slice,
      ContentPageDocument,
      GlobalsDocumentData,
      GlobalsDocumentDataMenuItem,
      GlobalsDocumentDataFooterPoliciesItem,
      GlobalsDocumentDataSocialLinksItem,
      GlobalsDocumentDataSlidesItem,
      GlobalsDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroImagesItem,
      HomepageDocumentDataIntroTextBlocksItem,
      HomepageDocumentDataSlices7Slice,
      HomepageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlices2Slice,
      LandingPageDocument,
      LegalDocumentData,
      LegalDocument,
      AllDocumentTypes,
      ContactBlockSliceDefaultPrimary,
      ContactBlockSliceDefault,
      ContactBlockSliceVariation,
      ContactBlockSlice,
      EmphasisBlockSliceDefaultPrimary,
      EmphasisBlockSliceDefault,
      EmphasisBlockSliceVariation,
      EmphasisBlockSlice,
      FullscreenTextWithImageBlockSliceDefaultPrimary,
      FullscreenTextWithImageBlockSliceDefault,
      FullscreenTextWithImageBlockSliceVariation,
      FullscreenTextWithImageBlockSlice,
      ImageCarouselBlockSliceDefaultItem,
      ImageCarouselBlockSliceDefault,
      ImageCarouselBlockSliceVariation,
      ImageCarouselBlockSlice,
      QuotesBlockSliceDefaultItem,
      QuotesBlockSliceDefault,
      QuotesBlockSliceVariation,
      QuotesBlockSlice,
      TestimonialBlockSliceDefaultPrimary,
      TestimonialBlockSliceDefault,
      TestimonialBlockSliceVariation,
      TestimonialBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceDefault,
      TextBlockSliceTextBlockWithCtaPrimary,
      TextBlockSliceTextBlockWithCta,
      TextBlockSliceVariation,
      TextBlockSlice,
      WideImageBlockSliceDefaultPrimary,
      WideImageBlockSliceDefault,
      WideImageBlockSliceVariation,
      WideImageBlockSlice,
    };
  }
}
