// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  fullscreen_text_with_image_block: defineAsyncComponent(
    () => import("./FullscreenTextWithImageBlock/index.vue")
  ),
  quotes_block: defineAsyncComponent(() => import("./QuotesBlock/index.vue")),
});
